abstract type AbstractServiceFormulation end

abstract type AbstractReservesFormulation<:AbstractServiceFormulation end

abstract type AbstractRegulationReserveFormulation<:AbstractReservesFormulation end

struct RampLimitedReserve<:AbstractReservesFormulation end

struct LoadProportionalReserve<:AbstractReservesForm end

struct SpinningReserve <:AbstractReservesForm end
