
LOG_GROUP_COST_FUNCTIONS = :CostFunctionsConstructor
LOG_GROUP_OPTIMZATION_CONTAINER = :OptimizationContainer
LOG_GROUP_TYPE_REGISTRATIONS = :TypeRegistrations
LOG_GROUP_FEEDFORWARDS_CONSTRUCTION = :FeedforwardConstructor
LOG_GROUP_BRANCH_CONSTRUCTIONS = :BranchConstructor
LOG_GROUP_SERVICE_CONSTUCTORS = :ServicesConstructor
LOG_GROUP_MODELS_VALIDATION = :ModelValidation
LOG_GROUP_OPTIMIZATION_CONTAINER = :OptimizationContainer
LOG_GROUP_BUILD_INITIAL_CONDITIONS = :InitialConditionsBuild
LOG_GROUP_NETWORK_CONSTRUCTION = :NetworkConstructor
LOG_GROUP_MODEL_STORE = :ModelStore
LOG_GROUP_RESULTS = :Results
LOG_GROUP_SIMULATION_STORE = :SimulationStore
