
LOG_GROUP_COST_FUNCTIONS = :CostFunctions
LOG_GROUP_INITIAL_CONDITIONS = :InitialConditions
LOG_GROUP_OPTIMZATION_CONTAINER = :OptimizationContainer
LOG_GROUP_TYPE_REGISTRATIONS = :TypeRegistrations
LOG_GROUP_FEEDFORWARDS_CONSTRUCTION = :FeedForward
LOG_GROUP_BRANCH_CONSTRUCTIONS = :BranchGroup
LOG_GROUP_SERVICE_CONSTUCTORS = :Services
LOG_GROUP_MODELS_VALIDATION = :ModelValidation
LOG_GROUP_OPTIMIZATION_CONTAINER = :OptimizationContainer
LOG_GROUP_BUILD_INITIAL_CONDITIONS = :InitialConditions
LOG_GROUP_NETWORK_CONSTRUCTION = :Network
